// <auto-generated />
using System;
using CMS.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.Persistence.Migrations
{
    [DbContext(typeof(CMSDbContext))]
    [Migration("20250418212026_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMS.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Admin Support"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Finance"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Maintenance"
                        });
                });

            modelBuilder.Entity("CMS.Domain.Entities.MasterApprovalMatrixContract", b =>
                {
                    b.Property<int>("MasterApprovalMatrixContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterApprovalMatrixContractId"));

                    b.Property<string>("ApproverId1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApproverId2")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApproverId3")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("MasterApprovalMatrixContractId");

                    b.HasIndex("ApproverId1");

                    b.HasIndex("ApproverId2");

                    b.HasIndex("ApproverId3");

                    b.HasIndex("DepartmentId");

                    b.ToTable("MasterApprovalMatrixContracts");
                });

            modelBuilder.Entity("CMS.Domain.Entities.MasterDocument", b =>
                {
                    b.Property<int>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValueId"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("ValueId");

                    b.ToTable("MasterDocuments");
                });

            modelBuilder.Entity("CMS.Domain.Entities.MasterEmployee", b =>
                {
                    b.Property<int>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValueId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmployeeMobile")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastPasswordChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ValueId");

                    b.ToTable("MasterEmployees");

                    b.HasData(
                        new
                        {
                            ValueId = 1,
                            DepartmentId = 100,
                            Email = "admin@cms.com",
                            EmployeeCode = "NEO1",
                            EmployeeExtension = "Main person",
                            EmployeeMobile = 7777766666L,
                            EmployeeName = "Admin",
                            IsDeleted = false,
                            LastPasswordChanged = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "AQAAAAIAAYagAAAAEFmmYzRXEyTghAw2lAZyvoRdnBiTZTNNtsMLMACE0XCdS6dowDG+pSnhMNhEhVAucA==",
                            Role = "Admin",
                            Unit = "Dadar"
                        },
                        new
                        {
                            ValueId = 2,
                            DepartmentId = 101,
                            Email = "sarthak@neosoft.com",
                            EmployeeCode = "NEO2",
                            EmployeeExtension = "IT Smart",
                            EmployeeMobile = 9999988888L,
                            EmployeeName = "Sarthak Lembhe",
                            IsDeleted = false,
                            LastPasswordChanged = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "AQAAAAIAAYagAAAAEN6pfxG4NPIHW2RyOt8EDhnzwuHuZB47x0+nSkLUEmVp0j2/ocPvIO9fcMa1+eFacQ==",
                            Role = "MOU_User",
                            Unit = "Dadar"
                        });
                });

            modelBuilder.Entity("CMS.Domain.Entities.MasterApprovalMatrixContract", b =>
                {
                    b.HasOne("CMS.Domain.Entities.MasterEmployee", "Approver1")
                        .WithMany()
                        .HasForeignKey("ApproverId1")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMS.Domain.Entities.MasterEmployee", "Approver2")
                        .WithMany()
                        .HasForeignKey("ApproverId2")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMS.Domain.Entities.MasterEmployee", "Approver3")
                        .WithMany()
                        .HasForeignKey("ApproverId3")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMS.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver1");

                    b.Navigation("Approver2");

                    b.Navigation("Approver3");

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
